apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: irene-2tier   
spec:
  type: ClusterIP
  selector:
    app: backend          # matches the label on backend Deployment
  ports:
    - port: 3000          # service port
      targetPort: 3000    # container port
